export default {
  decimal: ',',
  thousands: '\u00A0',
  grouping: [3],
  currency: ['', '\u00A0Kč'],
  dateTime: '%A,%e.%B %Y, %X',
  date: '%-d.%-m.%Y',
  dateSeparator: '.',
  time: '%H:%M:%S',
  periods: ['AM', 'PM'],
  days: ['neděle', 'pondělí', 'úterý', 'středa', 'čvrtek', 'pátek', 'sobota'],
  shortDays: ['ne.', 'po.', 'út.', 'st.', 'čt.', 'pá.', 'so.'],
  months: [
    'leden',
    'únor',
    'březen',
    'duben',
    'květen',
    'červen',
    'červenec',
    'srpen',
    'září',
    'říjen',
    'listopad',
    'prosinec'
  ],
  shortMonths: [
    'led',
    'úno',
    'břez',
    'dub',
    'kvě',
    'čer',
    'červ',
    'srp',
    'zář',
    'říj',
    'list',
    'pros'
  ],
  levels: [
    'Všechno',
    'Rok',
    'Čtvrťák',
    'Měsíc',
    'Týden',
    'Datum',
    'Hodina',
    'Minuta',
    'Sekunda',
    'Milisekunda'
  ],
  durationLongSuffix: [
    '',
    'roky',
    'čtvrtletí',
    'měsíce',
    'týdny',
    'dny',
    'hodiny',
    'minuty',
    'sekundy',
    'milisekundy'
  ],
  durationShortSuffix: ['', 'r', 'čt', 'mě', 't', 'd', 'h', 'm', 's', 'ms'],
  multi: ['.%L', ':%S', '%I:%M', '%I %p', '%a %d', 'W%G', '%b %d', '%B', '%Y']
};
