export default {
  decimal: ',',
  thousands: '.',
  grouping: [3],
  currency: ['', ' kr'],
  dateTime: '%A den %d %B %Y %X',
  date: '%d-%m-%Y',
  dateSeparator: '-',
  time: '%H:%M:%S',
  periods: ['AM', 'PM'],
  days: [
    'søndag',
    'mandag',
    'tirsdag',
    'onsdag',
    'torsdag',
    'fredag',
    'lørdag'
  ],
  shortDays: ['søn', 'man', 'tir', 'ons', 'tor', 'fre', 'lør'],
  months: [
    'januar',
    'februar',
    'marts',
    'april',
    'maj',
    'juni',
    'juli',
    'august',
    'september',
    'oktober',
    'november',
    'december'
  ],
  shortMonths: [
    'jan',
    'feb',
    'mar',
    'apr',
    'maj',
    'jun',
    'jul',
    'aug',
    'sep',
    'okt',
    'nov',
    'dec'
  ],
  levels: [
    'Alle',
    'År',
    'Kvartal',
    'Måned',
    'Uge',
    'Dato',
    'Time',
    'Minut',
    'Sekund',
    'Millisekund'
  ],
  durationLongSuffix: [
    '',
    'år',
    'kvartaler',
    'måneder',
    'uger',
    'dage',
    'timer',
    'minutter',
    'sekunder',
    'millisekunder'
  ],
  durationShortSuffix: ['', 'å', 'kv', 'må', 'u', 'd', 't', 'm', 's', 'ms'],
  multi: ['.%L', ':%S', '%I:%M', '%I %p', '%a %d', 'W%G', '%b %d', '%B', '%Y']
};
