export default {
  decimal: ',',
  thousands: '.',
  grouping: [3],
  currency: ['', '\u00A0€'],
  dateTime: '%A, der %e. %B %Y, %X',
  date: '%d.%m.%Y',
  dateSeparator: '.',
  time: '%H:%M:%S',
  periods: ['AM', 'PM'],
  days: [
    'Sonntag',
    'Montag',
    'Dienstag',
    'Mittwoch',
    'Donnerstag',
    'Freitag',
    'Samstag'
  ],
  shortDays: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
  months: [
    'Januar',
    'Februar',
    'März',
    'April',
    'Mai',
    'Juni',
    'Juli',
    'August',
    'September',
    'Oktober',
    'November',
    'Dezember'
  ],
  shortMonths: [
    'Jan',
    'Feb',
    'Mrz',
    'Apr',
    'Mai',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Okt',
    'Nov',
    'Dez'
  ],
  levels: [
    'Alles',
    'Jahr',
    'Quartal',
    'Monat',
    'Woche',
    'Tag',
    'Stunden',
    'Minute',
    'Sekunde',
    'Millisekunde'
  ],
  shortLevels: [
    'Alles',
    'Jahr',
    'Qtl',
    'Mnt',
    'Woche',
    'Tag',
    'St',
    'Min',
    'Sek',
    'Msek'
  ],
  durationLongSuffix: [
    '',
    'Jahre',
    'Quartalen',
    'Monate',
    'Wochen',
    'Tage',
    'Stunden',
    'Minuten',
    'Sekunden',
    'Millisekunden'
  ],
  durationShortSuffix: ['', 'j', 'q', 'mo', 'w', 't', 'st', 'm', 's', 'ms'],
  multi: ['.%L', ':%S', '%I:%M', '%I %p', '%a %d', 'W%G', '%b %d', '%B', '%Y']
};
