export default {
  decimal: ',',
  thousands: '\u00A0',
  grouping: [3],
  currency: ['', '\u00A0€'],
  dateTime: '%A, %-d. %Bta %Y klo %X',
  date: '%-d.%-m.%Y',
  dateSeparator: '.',
  time: '%H:%M:%S',
  periods: ['a.m.', 'p.m.'],
  days: [
    'sunnuntai',
    'maanantai',
    'tiistai',
    'keskiviikko',
    'torstai',
    'perjantai',
    'lauantai'
  ],
  shortDays: ['Su', 'Ma', 'Ti', 'Ke', 'To', 'Pe', 'La'],
  months: [
    'tammikuu',
    'helmikuu',
    'maaliskuu',
    'huhtikuu',
    'toukokuu',
    'kesäkuu',
    'heinäkuu',
    'elokuu',
    'syyskuu',
    'lokakuu',
    'marraskuu',
    'joulukuu'
  ],
  shortMonths: [
    'Tammi',
    'Helmi',
    'Maalis',
    'Huhti',
    'Touko',
    'Kesä',
    'Heinä',
    'Elo',
    'Syys',
    'Loka',
    'Marras',
    'Joulu'
  ],
  levels: [
    'Kaikki',
    'Vuosi',
    'Neljännes',
    'Kuukausi',
    'Viikko',
    'Päivämäärä',
    'Tunti',
    'Minuutti',
    'Sekunti',
    'Millisekunti'
  ],
  durationLongSuffix: [
    '',
    'vuodet',
    'neljännekset',
    'kuukaudet',
    'viikkot',
    'päivät',
    'tunnit',
    'minuutit',
    'sekunnit',
    'millisekuntia'
  ],
  durationShortSuffix: ['', 'vu', 'n', 'ku', 'vi', 'p', 't', 'm', 's', 'ms'],
  multi: ['.%L', ':%S', '%I:%M', '%I %p', '%a %d', 'W%G', '%b %d', '%B', '%Y']
};
