export default {
  decimal: ',',
  thousands: '\u00A0',
  grouping: [3],
  currency: ['', '\u00A0Ft'],
  dateTime: '%Y. %B %-e., %A %X',
  date: '%Y. %m. %d.',
  dateSeparator: '. ',
  time: '%H:%M:%S',
  periods: ['de.', 'du.'],
  days: [
    'vasárnap',
    'hétfő',
    'kedd',
    'szerda',
    'csütörtök',
    'péntek',
    'szombat'
  ],
  shortDays: ['V', 'H', 'K', 'Sze', 'Cs', 'P', 'Szo'],
  months: [
    'január',
    'február',
    'március',
    'április',
    'május',
    'június',
    'július',
    'augusztus',
    'szeptember',
    'október',
    'november',
    'december'
  ],
  shortMonths: [
    'jan.',
    'feb.',
    'már.',
    'ápr.',
    'máj.',
    'jún.',
    'júl.',
    'aug.',
    'szept.',
    'okt.',
    'nov.',
    'dec.'
  ],
  levels: [
    'Mind',
    'Év',
    'Negyed',
    'Hónap',
    'Hét',
    'Dátum',
    'Óra',
    'Perc',
    'Másodperc',
    'Ezredmásodperc'
  ],
  durationLongSuffix: [
    '',
    'évek',
    'negyedek',
    'hónapok',
    'hetek',
    'napok',
    'óra',
    'perc',
    'másodperc',
    'ezredmásodperc'
  ],
  durationShortSuffix: ['', 'é', 'ne', 'hó', 'he', 'na', 'ó', 'p', 'm', 'em'],
  multi: ['.%L', ':%S', '%I:%M', '%I %p', '%a %d', 'W%G', '%b %d', '%B', '%Y']
};
