export default {
  decimal: ',',
  thousands: '.',
  grouping: [3],
  currency: ['€', ''],
  dateTime: '%A %e %B %Y, %X',
  date: '%d/%m/%Y',
  dateSeparator: '/',
  time: '%H:%M:%S',
  periods: ['AM', 'PM'],
  days: [
    'Domenica',
    'Lunedì',
    'Martedì',
    'Mercoledì',
    'Giovedì',
    'Venerdì',
    'Sabato'
  ],
  shortDays: ['Dom', 'Lun', 'Mar', 'Mer', 'Gio', 'Ven', 'Sab'],
  months: [
    'Gennaio',
    'Febbraio',
    'Marzo',
    'Aprile',
    'Maggio',
    'Giugno',
    'Luglio',
    'Agosto',
    'Settembre',
    'Ottobre',
    'Novembre',
    'Dicembre'
  ],
  shortMonths: [
    'Gen',
    'Feb',
    'Mar',
    'Apr',
    'Mag',
    'Giu',
    'Lug',
    'Ago',
    'Set',
    'Ott',
    'Nov',
    'Dic'
  ],
  levels: [
    'Tutti',
    'Anno',
    'Trimestre',
    'Mese',
    'Settimana',
    'Data',
    'Ora',
    'Minuto',
    'Secondo',
    'Millisecondo'
  ],
  shortLevels: [
    'Tutti',
    'Anno',
    'Trim',
    'Mese',
    'Set',
    'Data',
    'Ora',
    'Min',
    'Sec',
    'Msec'
  ],
  durationLongSuffix: [
    '',
    'anni',
    'trimestri',
    'mesi',
    'settimane',
    'giorni',
    'ore',
    'minuti',
    'secondi',
    'millisecondi'
  ],
  durationShortSuffix: ['', 'a', 'tr', 'me', 'set', 'g', 'o', 'm', 's', 'ms'],
  multi: ['.%L', ':%S', '%I:%M', '%I %p', '%a %d', 'W%G', '%b %d', '%B', '%Y'],
  smartDateFormats: [
    {
      key: '%a %e %b %Y',
      lev1: '%Y',
      lev2: 'T%q-%Y',
      lev3: '%b %Y',
      lev4: 'Se %V-%G',
      lev5: '%a %e %b %Y',
      monthType: 'name',
      longText: false,
      weekday: true
    },
    {
      key: '%e %b %Y',
      lev1: '%Y',
      lev2: 'T%q-%Y',
      lev3: '%b %Y',
      lev4: 'Se %V-%G',
      lev5: '%e %b %Y',
      monthType: 'name',
      longText: false,
      weekday: false
    },
    {
      key: '%a %e %B %Y',
      lev1: '%Y',
      lev2: 'T%q-%Y',
      lev3: '%B %Y',
      lev4: 'Settimana %V, %G',
      lev5: '%a %e %B %Y',
      monthType: 'name',
      longText: true,
      weekday: true
    },
    {
      key: '%e %B %Y',
      lev1: '%Y',
      lev2: 'T%q-%Y',
      lev3: '%B %Y',
      lev4: 'Settimana %V, %G',
      lev5: '%e %B %Y',
      monthType: 'name',
      longText: true,
      weekday: false
    },
    {
      key: '%d/%m/%Y',
      lev1: '%Y',
      lev2: 'T%q/%Y',
      lev3: '%m/%Y',
      lev4: 'S%V/%G',
      lev5: '%d/%m/%Y',
      monthType: 'number',
      mmdd: false,
      separator: '/'
    },
    {
      key: '%d-%m-%Y',
      lev1: '%Y',
      lev2: 'T%q-%Y',
      lev3: '%m-%Y',
      lev4: 'S%V-%G',
      lev5: '%d-%m-%Y',
      monthType: 'number',
      mmdd: false,
      separator: '-'
    },
    {
      key: '%d.%m.%Y',
      lev1: '%Y',
      lev2: 'T%q.%Y',
      lev3: '%m.%Y',
      lev4: 'S%V.%G',
      lev5: '%d.%m.%Y',
      monthType: 'number',
      mmdd: false,
      separator: '.'
    },
    {
      key: '%d~%m~%Y',
      lev1: '%Y',
      lev2: 'T%q~%Y',
      lev3: '%m~%Y',
      lev4: 'S%V~%G',
      lev5: '%d~%m~%Y',
      monthType: 'number',
      mmdd: false,
      separator: '~'
    },
    {
      key: '%m/%d/%Y',
      lev1: '%Y',
      lev2: 'T%q/%Y',
      lev3: '%m/%Y',
      lev4: '%G/S%V',
      lev5: '%m/%d/%Y',
      monthType: 'number',
      mmdd: true,
      separator: '/'
    },
    {
      key: '%m-%d-%Y',
      lev1: '%Y',
      lev2: 'T%q-%Y',
      lev3: '%m-%Y',
      lev4: '%G-S%V',
      lev5: '%m-%d-%Y',
      monthType: 'number',
      mmdd: true,
      separator: '-'
    },
    {
      key: '%m.%d.%Y',
      lev1: '%Y',
      lev2: 'T%q.%Y',
      lev3: '%m.%Y',
      lev4: '%G.S%V',
      lev5: '%m.%d.%Y',
      monthType: 'number',
      mmdd: true,
      separator: '.'
    },
    {
      key: '%m~%d~%Y',
      lev1: '%Y',
      lev2: 'T%q~%Y',
      lev3: '%m~%Y',
      lev4: '%G~S%V',
      lev5: '%m~%d~%Y',
      monthType: 'number',
      mmdd: true,
      separator: '~'
    },
    {
      key: '%amd/%Y',
      lev1: '%Y',
      lev2: 'T%q/%Y',
      lev3: '%m/%Y',
      lev4: '%G/S%V',
      lev5: '%amd/%Y',
      monthType: 'number',
      mmdd: true,
      separator: '/'
    },
    {
      key: '%amd-%Y',
      lev1: '%Y',
      lev2: 'T%q-%Y',
      lev3: '%m-%Y',
      lev4: '%G-S%V',
      lev5: '%amd-%Y',
      monthType: 'number',
      mmdd: true,
      separator: '-'
    },
    {
      key: '%amd.%Y',
      lev1: '%Y',
      lev2: 'T%q.%Y',
      lev3: '%m.%Y',
      lev4: '%G.S%V',
      lev5: '%amd.%Y',
      monthType: 'number',
      mmdd: true,
      separator: '.'
    },
    {
      key: '%amd~%Y',
      lev1: '%Y',
      lev2: 'T%q~%Y',
      lev3: '%m~%Y',
      lev4: '%G~S%V',
      lev5: '%amd~%Y',
      monthType: 'number',
      mmdd: true,
      separator: '~'
    }
  ],
  smartTimeFormats: [
    {
      key: '%H:%M:%S.%L',
      lev6: '%H:00',
      lev7: '%H:%M',
      lev8: '%H:%M:%S',
      lev9: '%H:%M:%S.%L',
      ampm: false
    },
    {
      key: '%I:%M:%S.%L %p',
      lev6: '%I:00 %p',
      lev7: '%I:%M %p',
      lev8: '%I:%M:%S %p',
      lev9: '%I:%M:%S.%L %p',
      ampm: true
    }
  ]
};
