export default {
  decimal: '.',
  thousands: ',',
  grouping: [3],
  currency: ['₩', ''],
  dateTime: '%Y/%m/%d %a %X',
  date: '%Y/%m/%d',
  dateSeparator: '/',
  time: '%H:%M:%S',
  periods: ['오전', '오후'],
  days: ['일요일', '월요일', '화요일', '수요일', '목요일', '금요일', '토요일'],
  shortDays: ['일', '월', '화', '수', '목', '금', '토'],
  months: [
    '1월',
    '2월',
    '3월',
    '4월',
    '5월',
    '6월',
    '7월',
    '8월',
    '9월',
    '10월',
    '11월',
    '12월'
  ],
  shortMonths: [
    '1월',
    '2월',
    '3월',
    '4월',
    '5월',
    '6월',
    '7월',
    '8월',
    '9월',
    '10월',
    '11월',
    '12월'
  ],
  levels: [
    'All',
    'Year',
    'Quarter',
    'Month',
    'Week',
    'Date',
    'Hour',
    'Minute',
    'Second',
    'Millisecond'
  ],
  durationLongSuffix: [
    '',
    'years',
    'quarters',
    'months',
    'weeks',
    'days',
    'hours',
    'minutes',
    'seconds',
    'milliseconds'
  ],
  durationShortSuffix: ['', 'y', 'q', 'mo', 'w', 'd', 'h', 'm', 's', 'ms'],
  multi: ['.%L', ':%S', '%I:%M', '%I %p', '%a %d', 'W%G', '%b %d', '%B', '%Y']
};
