export default {
  decimal: ',',
  thousands: '.',
  grouping: [3],
  currency: ['€\u00A0', ''],
  dateTime: '%a %b %e %X %Y',
  date: '%d-%m-%Y',
  dateSeparator: '-',
  time: '%H:%M:%S',
  periods: ['AM', 'PM'],
  days: [
    'Zondag',
    'Maandag',
    'Dinsdag',
    'Woensdag',
    'Donderdag',
    'Vrijdag',
    'Zaterdag'
  ],
  shortDays: ['Zo', 'Ma', 'Di', 'Wo', 'Do', 'Vr', 'Za'],
  months: [
    'Januari',
    'Februari',
    'Maart',
    'April',
    'Mei',
    'Juni',
    'Juli',
    'Augustus',
    'September',
    'Oktober',
    'November',
    'December'
  ],
  shortMonths: [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'Mei',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Okt',
    'Nov',
    'Dec'
  ],
  levels: [
    'Alle',
    'Jaar',
    'Kwartaal',
    'Maand',
    'Week',
    'Dag',
    'Uur',
    'Minuut',
    'Seconde',
    'Milliseconde'
  ],
  shortLevels: [
    'Alle',
    'Jr',
    'Kw',
    'Mnd',
    'Wk',
    'Datum',
    'Uur',
    'Min',
    'Sec',
    'Msec'
  ],
  durationLongSuffix: [
    '',
    'jaren',
    'kwartalen',
    'maanden',
    'weken',
    'dagen',
    'uren',
    'minuten',
    'seconden',
    'milliseconden'
  ],
  durationShortSuffix: ['', 'j', 'kw', 'm', 'w', 'd', 'u', 'min', 's', 'ms'],
  multi: ['.%L', ':%S', '%I:%M', '%I %p', '%a %d', 'W%G', '%b %d', '%B', '%Y']
};
