export default {
  decimal: '.',
  thousands: ',',
  grouping: [3],
  currency: ['$', ''],
  dateTime: '%a %b %e %X %Y',
  date: '%m/%d/%Y',
  dateSeparator: '/',
  time: '%H:%M:%S',
  periods: ['AM', 'PM'],
  days: [
    'søndag',
    'mandag',
    'tirsdag',
    'onsdag',
    'torsdag',
    'fredag',
    'lørdag'
  ],
  shortDays: ['søn', 'man', 'tir', 'ons', 'tor', 'fre', 'lør'],
  months: [
    'januar',
    'februar',
    'mars',
    'april',
    'mai',
    'juni',
    'juli',
    'august',
    'september',
    'oktober',
    'november',
    'desember'
  ],
  shortMonths: [
    'jan',
    'feb',
    'mar',
    'apr',
    'maj',
    'jun',
    'jul',
    'aug',
    'sep',
    'okt',
    'nov',
    'des'
  ],
  levels: [
    'Alle',
    'År',
    'Kvartal',
    'Måned',
    'Uke',
    'Dato',
    'Time',
    'Minutt',
    'Sekund',
    'Millisekund'
  ],
  shortLevels: [
    'All',
    'År',
    'Kv',
    'Mn',
    'Uke',
    'Dat',
    'Time',
    'Min',
    'Sek',
    'Msek'
  ],
  durationLongSuffix: [
    '',
    'år',
    'kvartaler',
    'måneder',
    'uker',
    'dager',
    'timer',
    'minutter',
    'sekunder',
    'millisekunder'
  ],
  durationShortSuffix: ['', 'å', 'kv', 'må', 'u', 'd', 't', 'm', 's', 'ms'],
  multi: ['.%L', ':%S', '%I:%M', '%I %p', '%a %d', 'W%G', '%b %d', '%B', '%Y']
};
