export default {
  decimal: ',',
  thousands: '.',
  grouping: [3],
  currency: ['', 'zł'],
  dateTime: '%A, %e %B %Y, %X',
  date: '%d/%m/%Y',
  dateSeparator: '/',
  time: '%H:%M:%S',
  periods: ['AM', 'PM'],
  days: [
    'Niedziela',
    'Poniedziałek',
    'Wtorek',
    'Środa',
    'Czwartek',
    'Piątek',
    'Sobota'
  ],
  shortDays: ['Niedz.', 'Pon.', 'Wt.', 'Śr.', 'Czw.', 'Pt.', 'Sob.'],
  months: [
    'Styczeń',
    'Luty',
    'Marzec',
    'Kwiecień',
    'Maj',
    'Czerwiec',
    'Lipiec',
    'Sierpień',
    'Wrzesień',
    'Październik',
    'Listopad',
    'Grudzień'
  ],
  shortMonths: [
    'Stycz.',
    'Luty',
    'Marz.',
    'Kwie.',
    'Maj',
    'Czerw.',
    'Lipc.',
    'Sierp.',
    'Wrz.',
    'Paźdz.',
    'Listop.',
    'Grudz.'
  ],
  levels: [
    'Wszystkie',
    'Rok',
    'Kwartał',
    'Miesiąc',
    'Tydzień',
    'Data',
    'Godzina',
    'Minuta',
    'Sekunda',
    'Milisekunda'
  ],
  durationLongSuffix: [
    '',
    'lata',
    'kwartały',
    'miesiące',
    'tygodnie',
    'dni',
    'godziny',
    'minuty',
    'sekundy',
    'milisekundy'
  ],
  durationShortSuffix: ['', 'l', 'kw', 'mie', 't', 'd', 'g', 'm', 's', 'ms'],
  multi: ['.%L', ':%S', '%I:%M', '%I %p', '%a %d', 'W%G', '%b %d', '%B', '%Y']
};
