export default {
  decimal: ',',
  thousands: '\u00A0',
  grouping: [3],
  currency: ['', 'SEK'],
  dateTime: '%A den %d %B %Y %X',
  date: '%Y-%m-%d',
  dateSeparator: '-',
  time: '%H:%M:%S',
  periods: ['fm', 'em'],
  days: ['Söndag', 'Måndag', 'Tisdag', 'Onsdag', 'Torsdag', 'Fredag', 'Lördag'],
  shortDays: ['Sön', 'Mån', 'Tis', 'Ons', 'Tor', 'Fre', 'Lör'],
  months: [
    'Januari',
    'Februari',
    'Mars',
    'April',
    'Maj',
    'Juni',
    'Juli',
    'Augusti',
    'September',
    'Oktober',
    'November',
    'December'
  ],
  shortMonths: [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'Maj',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Okt',
    'Nov',
    'Dec'
  ],
  levels: [
    'Alla',
    'År',
    'Kvartal',
    'Månad',
    'Vecka',
    'Datum',
    'Timme',
    'Minut',
    'Іekund',
    'Millisekund'
  ],
  durationLongSuffix: [
    '',
    'år',
    'kvartal',
    'månader',
    'veckor',
    'dagar',
    'timmar',
    'minuter',
    'sekunder',
    'millisekunder'
  ],
  durationShortSuffix: ['', 'å', 'kv', 'må', 'v', 'd', 't', 'm', 's', 'ms'],
  multi: ['.%L', ':%S', '%I:%M', '%I %p', '%a %d', 'W%G', '%b %d', '%B', '%Y']
};
