export default {
  decimal: '.',
  thousands: ',',
  grouping: [3],
  currency: ['₺', ''],
  dateTime: '%a %e %b %X %Y',
  date: '%d/%m/%Y',
  dateSeparator: '/',
  time: '%H:%M:%S',
  periods: ['AM', 'PM'],
  days: [
    'Pazar',
    'Pazartesi',
    'Salı',
    'Çarşamba',
    'Perşembe',
    'Cuma',
    'Cumartesi'
  ],
  shortDays: ['Paz', 'Pzt', 'Sal', 'Çar', 'Per', 'Cum', 'Cmt'],
  months: [
    'Ocak',
    'Şubat',
    'Mart',
    'Nisan',
    'Mayıs',
    'Haziran',
    'Temmuz',
    'Ağustos',
    'Eylül',
    'Ekim',
    'Kasım',
    'Aralık'
  ],
  shortMonths: [
    'Oca',
    'Şub',
    'Mar',
    'Nis',
    'May',
    'Haz',
    'Tem',
    'Ağu',
    'Eyl',
    'Eki',
    'Kas',
    'Ara'
  ],
  levels: [
    'Hepsi',
    'Yıl',
    'Çeyrek',
    'Ay',
    'Hafta',
    'Tarih',
    'Saat',
    'Dakika',
    'Saniye',
    'Milisaniye'
  ],
  shortLevels: [
    'Hepsi',
    'Yıl',
    'Çyr',
    'Ay',
    'Hft',
    'tar',
    'sa',
    'dk',
    'sn',
    'ms'
  ],
  durationLongSuffix: [
    '',
    'yıl',
    'çeyrek',
    'ay',
    'hafta',
    'gün',
    'saat',
    'dakika',
    'saniye',
    'milisaniye'
  ],
  durationShortSuffix: ['', 'y', 'çe', 'ay', 'h', 'g', 'sa', 'd', 's', 'ms'],
  multi: ['.%L', ':%S', '%I:%M', '%I %p', '%a %d', 'W%G', '%b %d', '%B', '%Y']
};
